name: esmfold_2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - ipython
  - ipykernel
  - jupyter_client
  - traitlets
  - prompt-toolkit
  - pygments
  - matplotlib-inline
  - openmm
  - pdbfixer
  - hmmer
  - hhsuite
  - kalign2
  - fftw
  - ca-certificates
  - openssl
  - libxml2
  - yaml
  - xz
  - libiconv
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - libsqlite
  - sqlite
  - libzlib
  - liblzma
  - ncurses
  - readline
  - tbb
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.8
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==24.2.0
      - biopython==1.79
      - bitarray==3.3.1
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.15.1
      - charset-normalizer==2.0.12
      - click==8.1.8
      - contextlib2==21.6.0
      - cycler==0.11.0
      - cython==3.0.12
      - deepspeed==0.5.9
      - dllogger==1.1.0
      - dm-tree==0.1.6
      - docker-pycreds==0.4.0
      - fair-esm==2.0.1
      - fairseq==0.12.2
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.39.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.3
      - hjson==3.1.0
      - hydra-core==1.0.7
      - idna==3.10
      - kiwisolver==1.4.5
      - lxml==5.3.2
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - ml-collections==0.1.0
      - multidict==6.0.5
      - ninja==1.11.1.4
      - oauthlib==3.2.2
      - omegaconf==2.0.6
      - pathtools==0.1.2
      - pillow==9.5.0
      - portalocker==2.7.0
      - promise==2.3
      - protobuf==3.20.3
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydeprecate==0.3.1
      - pyparsing==3.1.4
      - pytorch-lightning==1.5.10
      - pyyaml
